<?php
ob_start();
$u=$_POST['userid'];
$p=$_POST['pass'];
$user_name="bc735e9a1d9622";
$password="47acc5cd";
$db="rachitdb";
$c=mysqli_connect('us-cdbr-azure-southcentral-f.cloudapp.net',$user_name,$password,$db);
?>
